title: Hugo's Website
description: Writings and notes
url: "" # Set to https://yourusername.github.io when deploying
baseurl: "/hugos-website" # Remove this line if using a custom domain

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  math_engine: null  # We'll use MathJax instead
  footnote_nr: 1

# Build settings
permalink: /:title/
